# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\"\x07\n\x05\x45mpty\"\x19\n\x0bTermRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"V\n\x0e\x41\x64\x64TermRequest\x12\x0c\n\x04term\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x10\n\x08\x65xamples\x18\x04 \x01(\t\"X\n\x04Term\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\t\x12\x12\n\ndefinition\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x10\n\x08\x65xamples\x18\x05 \x01(\t\"N\n\x0cTermResponse\x12\x1c\n\x04term\x18\x01 \x01(\x0b\x32\x0e.glossary.Term\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"P\n\rTermsResponse\x12\x1d\n\x05terms\x18\x01 \x03(\x0b\x32\x0e.glossary.Term\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2\x82\x02\n\x0fGlossaryService\x12\x38\n\x07GetTerm\x12\x15.glossary.TermRequest\x1a\x16.glossary.TermResponse\x12\x37\n\x0bGetAllTerms\x12\x0f.glossary.Empty\x1a\x17.glossary.TermsResponse\x12?\n\x0bSearchTerms\x12\x17.glossary.SearchRequest\x1a\x17.glossary.TermsResponse\x12;\n\x07\x41\x64\x64Term\x12\x18.glossary.AddTermRequest\x1a\x16.glossary.TermResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_TERMREQUEST']._serialized_start=37
  _globals['_TERMREQUEST']._serialized_end=62
  _globals['_SEARCHREQUEST']._serialized_start=64
  _globals['_SEARCHREQUEST']._serialized_end=94
  _globals['_ADDTERMREQUEST']._serialized_start=96
  _globals['_ADDTERMREQUEST']._serialized_end=182
  _globals['_TERM']._serialized_start=184
  _globals['_TERM']._serialized_end=272
  _globals['_TERMRESPONSE']._serialized_start=274
  _globals['_TERMRESPONSE']._serialized_end=352
  _globals['_TERMSRESPONSE']._serialized_start=354
  _globals['_TERMSRESPONSE']._serialized_end=434
  _globals['_GLOSSARYSERVICE']._serialized_start=437
  _globals['_GLOSSARYSERVICE']._serialized_end=695
# @@protoc_insertion_point(module_scope)
